### ISSUE TITLE
Nice code

### ISSUE THREAD

**Issue by hassyGo** [rajarsheem/joint-many-task-model#1]
Hi, I'm Kazuma, the first author of the joint many-task paper.
Thank you for your interest in our paper.
If you have any questions, please feel free to tell me.

Please note that our paper was not accepted by ICLR2017, so the README file could be slightly modified :)

Thanks,
  Kazuma

**Comment by rajarsheem** [comment]
Hello Kazuma. I removed ICLR from the README. In spite of it not being accepted by ICLR, I feel it's a great paper :smile: 

Indeed I have few questions to ask you. Do you have any mail ID ? 

Rajarshee.

**Comment by hassyGo** [comment]
Thanks.
Sure, all information is available at my github page: @hassyGo

I might be able to answer questions when I have time.
